Initial split of 'desktop.py'
It seems to almost be fully functional, other than `source.ui.desktop.main.app` is still set to None due to utility being imported (which imports itself) before `...desktop.main.app` is set. This is most certainly a circular import issue

[12:29:21 AM] [FATAL] [core: main.app_crash               ] auto-mcs has crashed with exception code:  0d-6b98d9
   >  'NoneType' object has no attribute 'exit_check'
   >  Traceback:
   >  Traceback (most recent call last):
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/source/launcher.py", line 571, in foreground
   >      ui_loop()
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/source/ui/main.py", line 51, in ui_loop
   >      run_application()
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/source/ui/desktop/main.py", line 397, in run_application
   >      raise e
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/source/ui/desktop/main.py", line 389, in run_application
   >      app.run()
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/build-tools/venv/lib/python3.12/site-packages/kivy/app.py", line 956, in run
   >      runTouchApp()
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/build-tools/venv/lib/python3.12/site-packages/kivy/base.py", line 574, in runTouchApp
   >      EventLoop.mainloop()
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/build-tools/venv/lib/python3.12/site-packages/kivy/base.py", line 339, in mainloop
   >      self.idle()
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/build-tools/venv/lib/python3.12/site-packages/kivy/base.py", line 383, in idle
   >      self.dispatch_input()
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/build-tools/venv/lib/python3.12/site-packages/kivy/base.py", line 334, in dispatch_input
   >      post_dispatch_input(*pop(0))
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/build-tools/venv/lib/python3.12/site-packages/kivy/base.py", line 302, in post_dispatch_input
   >      wid.dispatch('on_touch_up', me)
   >    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/build-tools/venv/lib/python3.12/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
   >      self.dispatch('on_release')
   >    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/source/ui/desktop/widgets.py", line 4692, in execute
   >      button_action(name, self.button)
   >    File "/Users/kaleb/Documents/GitHub/auto-mcs/source/ui/desktop/widgets.py", line 7870, in button_action
   >      if not main.app.exit_check(): main.exit_app()
   >             ^^^^^^^^^^^^^^^^^^^
   >  AttributeError: 'NoneType' object has no attribute 'exit_check'